SELECT TOP (1000) [Month]
      ,[OrganizationName]
      ,[CustomerType]
      ,[OfferType]
      ,[SubscriptionCount]
      ,[UserCount]
      ,[CategoryCount]
      ,[FeatureCount]
      ,[NewCustomer]
      ,[ExistingCustomer]
      ,[ChurnedCustomer]
      ,[ChurnMonth]
  FROM [dbo].[v_MLSynapseTelemetryCustomerAnalysis]